# Generated by Django 5.1.1 on 2024-10-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0002_profile_journal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='cotent',
            new_name='content',
        ),
    ]
