# Generated by Django 5.1.1 on 2024-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0003_rename_cotent_journal_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
