# Generated by Django 5.1.1 on 2024-10-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0004_alter_journal_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
